version: '3.8'
services:
  react_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: react_app_dev
    volumes:
      - ./src:/app/src:ro
    env_file:
      - ./env/.dev.env
    ports:
      - 3000:3000

# docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d
# docker-compose -f docker-compose.yml -f docker-compose.dev.yml down
# docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build