version: '3.8'
services:
  react_app:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_NAME=lewis-prod
    container_name: react_app_prod
    env_file:
      - ./env/.prod.env
    ports:
      - 8080:80

# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
# docker-compose -f docker-compose.yml -f docker-compose.prod.yml down
# docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build